---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
  roles:
    - { role: swapfile, SWAPFILE_SIZE: "2GB" }
    - role: nginx
      nginx_sites:
      - cms
      - lms
      nginx_default_sites:
      - lms
    - role: mysql
      when: EDXAPP_MYSQL_HOST == 'localhost'
    - edxlocal
    - role: mongo
      when: "'localhost' in EDXAPP_MONGO_HOSTS"
    - edxapp
